name: ci-laravel-workflow
on: [pull_request]
jobs:
  chek-application:
    runs-on: ubuntu-20.04
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.0

    services:
      db:
        image: mysql:8.0
        env:
          DB_CONNECTION: mysql
          DB_HOST: db
          DB_PORT: 3306
          DB_DATABASE: code_micro_videos_test
          DB_USERNAME: root
          DB_PASSWORD: root
        ports:
          - 33306:3306

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: install composer/npm dependencies
        run: |
          chmod -R 777 .
          composer install --no-scripts
          npm install

      - name: Prepare Laravel Application
        run: |
          php artisan key:generate
          php artisan migrate --env=testing

      - name: Run tests using PHPUnit
        run: vendor/bin/phpunit
