name: ci-laravel-workflow
on: [pull_request]
jobs:
  chek-application:
    runs-on: ubuntu-20.04

    services:
      db:
        image: mysql:8.0
        env:
          DB_CONNECTION: mysql
          DB_HOST: localhost
          DB_PORT: 3306
          DB_DATABASE: code_micro_videos
          DB_USERNAME: root
          DB_PASSWORD: root
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: install composer/npm dependencies
        run: |
          chmod -R 777 .
          composer install --no-scripts
          npm install

      - name: Prepare Laravel Application
        run: |
          php artisan key:generate
          php artisan migrate

      - name: Run tests using PHPUnit
        run: vendor/bin/phpunit
